name: Build OCI .Net 6
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devopenspace2023
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          # Wir wollen .Net 6.0.x
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore DemoApp/Server/src/Server.csproj
      - name: Build
        run: dotnet build -c -release --no-restore DemoApp/Server/src/Server.csproj
      - name: Publish
        run: dotnet publish -o DemoApp/Server/out DemoApp/Server/src/Server.csproj
      - name: Login to Github Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=v1.0.0          
            type=raw,value=latest          
      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: ./DemoApp/Server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
