name: demo with parameter  
on:
  push:
    branches: [ main ]
jobs:
  echo-parameter:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step-1
        run: echo "field_step_one=My Value Is 42" >> $GITHUB_OUTPUT
      - name: step two
        run: echo "my out value is ${{ steps.step-1.output.field_step_one }}"
