name: demo-10
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  jobSource:
    runs-on: ubuntu-latest
    
    steps:
      - id: step1
        name: Step 1
        run: echo "varInStep=hallo world" >> $GITHUB_OUTPUT
        shell: pwsh
    outputs:
      greeting: ${{ steps.step1.outputs.varInStep }}
  jobTarget:
    runs-on: ubuntu-latest
    needs: jobSource
    steps:
      - run: echo ${{needs.jobSource.outputs.greeting}}
